### ISSUE TITLE
Injeção de dependência

### ISSUE THREAD

**Issue by arthurs159** [SannyHL/sistema-vendas#1]
Oi Sanny, percebi no seu projeto que você faz a injeção de dependência e também usa no seu construtor, acho que você poderia mandar apenas no construtor deixando a injeção em uma parte só.

Por exemplo:
![image](https://user-images.githubusercontent.com/77133022/190809641-9df0e703-5f13-474b-8e52-d7ee76822de7.png)

**Comment by SannyHL** [comment]
Muito obrigada pela sujestão! Na verdade nesse projeto eu estava entrando do mundo do Spring Boot, depois tenho que voltar nele para atualizar, não somente nele. Aí farei as adequações assim que possível. 
Um abraço 🚀

**Comment by SannyHL** [comment]
Ei @arthurs159, agradeço novamente pelo feedback! Realizei as adequações 🚀
